version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${EXPOSED_PORT}:${PORT}

  postgres:
    image: postgres:13
    volumes:
      - postgres-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

volumes:
  postgres-app-data:
