version: "3"

services:
  app:
    image: golang:1.15.4
    command:
      [
        "./wait-for-it.sh",
        "${POSTGRES_HOST}:${POSTGRES_PORT}",
        "--",
        "go",
        "run",
        "main.go",
      ]
    ports:
      - ${EXPOSED_PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT:
      GIN_MODE:

  postgres:
    image: postgres:13
    volumes:
      - postgres-app-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:

volumes:
  postgres-app-data:
